<?php

namespace Database\Seeders;

use App\Models\Humanos\County;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipios = collect()
        ->push('Acala')
        ->push('Acacoyagua')
        ->push('Acacapetahua')
        ->push('Aldama')
        ->push('Altamirano')
        ->push('Amatán')
        ->push('Amatenango de la Frontera')
        ->push('Amatenango del Valle')
        ->push('Ángel Albino Corzo')
        ->push('Arriaga')
        ->push('Bejucal de Ocampo')
        ->push('Belisario Domínguez')
        ->push('Bellavista')
        ->push('Benemérito de las Américas')
        ->push('Berriozábal')
        ->push('Bochil')
        ->push('Cacahoatán')
        ->push('Catazajá')
        ->push('Chalchihuitán')
        ->push('Chamula')
        ->push('Chanal')
        ->push('Chapultenango')
        ->push('Chenalhó')
        ->push('Chiapa de Corzo')
        ->push('Chiapilla')
        ->push('Chicoasen')
        ->push('Chicomuselo')
        ->push('Chilón')
        ->push('Cintalapa de Figueroa')
        ->push('Coapilla')
        ->push('Comitán de Domínguez')
        ->push('Copainalá')
        ->push('El Bosque')
        ->push('El Porvenir')
        ->push('Emiliano Zapata')
        ->push('Escuintla')
        ->push('Francisco León')
        ->push('Frontera Comalapa')
        ->push('Frontera Hidalgo')
        ->push('Huehuetán')
        ->push('Huitiupán')
        ->push('Huixtán')
        ->push('Huixtla')
        ->push('Ixhuatán')
        ->push('Ixtacomitán')
        ->push('Ixtapa')
        ->push('Ixtapangajoya')
        ->push('Jiquipilas')
        ->push('Jitotol')
        ->push('Juárez')
        ->push('La concordia')
        ->push('La Grandeza')
        ->push('La Independencia')
        ->push('La Libertad')
        ->push('La Trinitaria')
        ->push('Larrainzar')
        ->push('Las Margaritas')
        ->push('Las Rosas')
        ->push('Mapastepec')
        ->push('Maravilla Tenejapa')
        ->push('Marqués de Comillas')
        ->push('Mazapa de Madero')
        ->push('Mazatán')
        ->push('Metapa')
        ->push('Mezcalapa')
        ->push('Mitontic')
        ->push('Montecristo de Guerrero')
        ->push('Motozintla')
        ->push('Nicolás Ruíz')
        ->push('Ocosingo')
        ->push('Ocotepec')
        ->push('Ocozocoautla de Espinoza')
        ->push('Ostuacán')
        ->push('Osumacinta')
        ->push('Oxchuc')
        ->push('Palenque')
        ->push('Pantelhó')
        ->push('Pantepec')
        ->push('El Parral')
        ->push('Pichucalco')
        ->push('Pijijiapan')
        ->push('Pueblo Nuevo Solistahuacán')
        ->push('Rayón')
        ->push('Reforma')
        ->push('Sabanilla')
        ->push('Salto de Agua')
        ->push('San Cristóbal de las Casas')
        ->push('San Fernando')
        ->push('San Juan Cancuc')
        ->push('San Lucas')
        ->push('Santiago el Pinar')
        ->push('Siltepec')
        ->push('Simojovel')
        ->push('Sitalá')
        ->push('Socoltenango')
        ->push('Solosuchiapa')
        ->push('Soyaló')
        ->push('San Andrés Duraznal')
        ->push('Suchiapa')
        ->push('Suchiate')
        ->push('Sunuapa')
        ->push('Tapachula')
        ->push('Tapalapa')
        ->push('Tapilula')
        ->push('Tecpatán')
        ->push('Tenejapa')
        ->push('Teopisca')
        ->push('Tila')
        ->push('Tonalá')
        ->push('Totolapa')
        ->push('Tumbalá')
        ->push('Tuxtla Chico')
        ->push('Tuxtla Gutiérrez')
        ->push('Tuzantán')
        ->push('Tzimol')
        ->push('Unión Juárez')
        ->push('Venustiano Carranza')
        ->push('Villa Comaltitlán')
        ->push('Villa Corzo')
        ->push('Villaflores')
        ->push('Yajalón')
        ->push('Zinacantán');
        foreach($municipios as $municipio){
            $str = Str::upper($municipio);
            County::create([
                'name'=>$str,
                'state_id' => 7,
                'status'=>'active',
                'modified_by'=>'david@fideicomiso.com',
            ]);
        };
    }
}
